### ISSUE TITLE
key name changed - please fix it

### ISSUE THREAD

**Issue by jan-panoch** [KBB-GmbH/yaps-ceph#1]
2  yapscephprtg.py
 @@ -56,7 +56,7 @@ def main(sJson):
      m = ''
      h = { 
          'HEALTH_OK' : 0, 'HEALTH_WARN' : 1, 'HEALTH_ERR' : 2 
 -    }[ j['health']['status'] ]
 +    }[ j['health']['overall_status'] ]
      e = max(e,h)
      if e > 0:
          m += 'situation occured'

**Comment by jeichhor-workin** [comment]
Ahoi Jan,
as far as i understood overall_status is pre-luminous and thereby outdated, whereas status is luminous compliant. 
http://lists.ceph.com/pipermail/ceph-users-ceph.com/2017-September/021011.html
So I wouldn't consider this an issue.

Regards, Joerg

**Comment by jan-panoch** [comment]
yes, you are right. but on my ceph version 10.2.7 it's handled as 'overall_status'
maybe following construct can cover both versions - older and new:

channels = []                                                                                                                                                       |
    e = 0                                                                                                                                                               |
    m = ''                                                                                                                                                              |
    if 'status' in j['health'].keys():                                                                                                                                  |
        sk = 'status'                                                                                                                                                   |
    else:                                                                                                                                                               |
        sk = 'overall_status'                                                                                                                                           |
    h = {                                                                                                                                                               |
        'HEALTH_OK' : 0, 'HEALTH_WARN' : 1, 'HEALTH_ERR' : 2                                                                                                            |
    }[ j['health'][sk] ]                                                                                                                                                |
    e = max(e,h)

**Comment by jeichhor-workin** [comment]
Ahoi Jan, yould you please add a testfile - at best one with ok and one with warn - and provide a pull-request? Thanks, Joerg

**Comment by kbbit** [comment]
please reopen, if needed
