### ISSUE TITLE
Sensor reporting "no data" then error occurs 

### ISSUE THREAD

**Issue by martinohansen** [KBB-GmbH/yaps-ceph#3]
First of all thanks for the monitering script, we find it very useful. 

The following sensor output will result in a sensor reporting "no data" on all channels, https://i.imgur.com/jm70OE0.jpeg, therefore rendering us unable to get data then the cluster fails. Is it possible to avoid this scenario, making us able to get data then the cluster is in error state?

`{"prtg": {"text": "situation occured", "result": [{"value": 1, "channel": "status"}, {"value": 0, "channel": "missing_osds"}, {"value": 60443019919360, "channel": "bytes_avail"}, {"value": 150115459686400, "channel": "bytes_used"}, {"value": 58726563, "channel": "read_bytes_sec"}, {"value": 14145524, "channel": "write_bytes_sec"}, {"value": 14337, "channel": "read_op_per_sec"}, {"value": 38, "channel": "write_op_per_sec"}, {"value": 0, "channel": "recovering_bytes_per_sec"}, {"value": 0, "channel": "recovering_objects_per_sec"}, {"value": 17884825, "channel": "num_objects"}, {"value": 0, "channel": "misplaced_objects"}, {"value": 0, "channel": "degraded_objects"}], "error": 1}}`

Thanks,
Martin

**Comment by jeichhor-workin** [comment]
Hi Martin,

your cluster reported a state, which was not healthy and the error was not in ( 'OBJECT_MISPLACED','PG_DEGRADED'). If the sensor gives you an error, you should always check "ceph -s".

The latest version should only report errors, if ceph is in error state. 
But prtg in general writes no information, when sensor is in error state.

Regards, Joerg

**Comment by martinohansen** [comment]
Maybe a version that never enters an error state could be a solution? That way we could make a simple sensor for checking the cluster health and use this sensor for gathering data.

Thank,
Martin

**Comment by jeichhor-workin** [comment]
Hi Martin,
the latest commit solve your issue - prtg error should only occur on sensor error - ceph HEALTH_ERR needs to be set by error/warning level on "channel": "status"
Regards, Jorg
