### ISSUE TITLE
Multiple warnings reported by ceph health, sensor still green

### ISSUE THREAD

**Issue by jhuesser** [KBB-GmbH/yaps-ceph#4]
Hi there,
Is this script still maintained? We've just set it up tho monitor our cephalopods cluster. The Cluster state is know HEALTH_WARN, reporting 3 warnings, but yet the sensor is still green.

The warnings get reported to PRTG as, the messages are visible in the overview but the status doesn't change.

**Comment by jeichhor-workin** [comment]
Hi,
I'd expext the value of the channel "status" =1. Can you confirm?`
If so, you need to set limits in PRTG accordingly: >0 Warn, >1 Error
![image](https://user-images.githubusercontent.com/12509928/76954375-8893c400-6910-11ea-842d-b6f40c4daf0f.png)

Regards

**Comment by jhuesser** [comment]
Ah sorry, my bad I thought the script returns tis format https://kb.paessler.com/en/topic/41793-custom-script:-return-value-from-linux-server-using-ssh.
I've changed the channel settings, now the status is on warning, thanks!

However the sensor is still green, but status is the primary channel. May you have a clue why? Thanks!

**Comment by jhuesser** [comment]
Never mind, took a very long time to refresh...
